[package]
name = "abm"
version.workspace = true
edition.workspace = true

[dependencies]
faer = { workspace = true }
clebsch-gordan = { workspace = true }
quantum = { path = "../quantum", features = ["spins", "faer"] }