[package]
name = "benches"
version = "0.1.0"
edition = "2021"

[dependencies]
scattering-solver = { path = "../scattering-solver/" }
faer = { version = "0.20" }
dhat = {version = "0.3", optional = true}

[features]
default = []
allocations = ["dep:dhat"]